Goorm_Project/urls.py
from django.contrib import admin
from django.urls import path, include
import main.views
import accounts.views
import goorm.views
from django.conf import settings
from django.conf.urls.static import static

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('accounts.urls')),
    path('goorm/', include('goorm.urls')),
  
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

goorm/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'goorm'

urlpatterns = [
    path('goormlist',views.goormlist, name='goormlist'),
    path('<int:tobacco_id>', views.detail, name='detail'),
    path('new', views.new, name='new'),
    path('create', views.create, name='create'),
    path('brand_detail/<str:brand_id>', views.brand_filter, name='brand_filter'),
    path('delete/<int:tobacco_id>', views.delete, name='delete'),
    path('comment_delete/<int:comment_id>', views.comment_delete, name='comment_delete'),
    path('comment_update/<int:comment_id>', views.comment_update, name='comment_update'),
    path('search/', views.search, name='search'),
    path('edit/<int:tobacco_id>', views.edit, name='edit'),
    path('update/<int:tobacco_id>', views.update, name='update'),
]

main/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('',views.home, name = 'home'),
    path('save_log',views.save_log, name='save_log'),
]

goorm/models.py
from django.db import models
from accounts.models import Profile
from django_fields import DefaultStaticImageField


class Brand(models.Model):
    brd_name = models.CharField(max_length=100)
    brd_img = DefaultStaticImageField(upload_to='brand_img/', blank=True, default_image_path='images/default_goorm_img.png')

    def __str__(self):
        return self.brd_name

class Tobacco(models.Model):
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE, related_name='tobacco')
    name = models.CharField(max_length=50)
    price = models.IntegerField(blank=True)
    # rel_date = models.CharField(max_length=100)
    nicotine =  models.FloatField()
    TAR = models.FloatField()
    feel_of_hit = models.CharField(max_length=10)
    score = models.FloatField(default=0)
    isMenthol = models.BooleanField(default = False)
    img = DefaultStaticImageField(upload_to='goorm_img/', blank=True, default_image_path='images/default_goorm_img.png')
    
    def __str__(self):
        return self.name

class Comment(models.Model) :
    tobacco = models.ForeignKey(Tobacco, on_delete = models.CASCADE, related_name= 'comments')
    writer = models.ForeignKey(Profile, on_delete = models.CASCADE, related_name= 'writer')
    pub_date = models.DateTimeField(auto_now_add= True)
    contents = models.TextField()
    score = models.PositiveIntegerField(default=3)


    def __str__(self) :
        return self.writer.username

# Create your models here.

goorm/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Tobacco, Comment, Brand
from django.contrib.auth.decorators import login_required

def goormlist(request):
    grm_list = Tobacco.objects.all()
    brd_list = Brand.objects.all()

    brd_grm = []
    for brd in brd_list:
        tmps = []
        tmps.append(brd)
        grm_info = grm_list.filter(brand = brd)

        for grm in grm_info:    
            score_star = score_trans(grm.score)
            grm.star = score_star

        tmps.append(grm_info)
        brd_grm.append(tmps)

    return render(request, 'goorm/list.html', {'grm_list': grm_list, 'brd_grm': brd_grm, 'brd_list':brd_list})

def score_trans(score):
    if score < 2:
        return '★☆☆☆☆'
    elif 2 <= score < 3:
        return '★★☆☆☆'
    elif 3 <= score < 4:   
        return '★★★☆☆'
    elif 4 <= score < 5:
        return '★★★★☆'    
    else:
        return '★★★★★'

def detail(request, tobacco_id):
    
    # POST(comment 생성)
    if request.method == "POST" :
        tobacco_detail = get_object_or_404(Tobacco, pk=tobacco_id)
        
        # create comment 
        comment = Comment()
        comment.tobacco = Tobacco.objects.get(id = tobacco_id)
        comment.writer = request.user
        comment.contents = request.POST['comment_text']
        comment.score = request.POST['comment_score']
        comment.save()

        comments = Comment.objects.filter(tobacco=tobacco_id)
    
    # GET
    else:
        tobacco_detail = get_object_or_404(Tobacco, pk=tobacco_id)
        comments = Comment.objects.filter(tobacco=tobacco_id)

    # 구름과자 score 계산 로직
    num_of_cmt = len(comments)
    total_score = 0
    for cmt in comments:
        total_score += cmt.score
    if total_score != 0:
        total_score = total_score / num_of_cmt
    tobacco_detail.score = total_score
    tobacco_detail.save()

    cmt_flag = False
    for cmt in comments:
        if request.user == cmt.writer:
            cmt_flag = True 

    return render(request, 'goorm/detail.html',{'tobacco': tobacco_detail, 'comments':comments, 'cmt_flag':cmt_flag})

@login_required
def new(request):
    if request.user.username == 'admin':
        brands = Brand.objects.all()
        return render(request, 'goorm/new.html', {'brands':brands} )
    else:
        err = '권한이 없습니다.'
        return render(request, 'accounts/error.html', {'err':err} )
    

def create(request):
    if request.POST['brand']=='isNewBrand':
        selected_brand = Brand()
        selected_brand.brd_name = request.POST['newBrand']
        selected_brand.save()
    else:
        selected_brand = Brand.objects.get(brd_name=request.POST['brand'])
    
    new_tobacco = Tobacco()
    new_tobacco.brand = selected_brand
    new_tobacco.name = request.POST['name']
    new_tobacco.price = request.POST['price']
    # new_tobacco.rel_date = request.POST['rel_date']
    new_tobacco.nicotine = request.POST['nicotine']
    new_tobacco.TAR = request.POST['TAR']
    new_tobacco.feel_of_hit = request.POST['feel_of_hit']
    new_tobacco.img = request.FILES.get('tobacco_img')
    if request.POST['isMenthol'] == 'yes':
       new_tobacco.isMenthol = True
    else:
       new_tobacco.isMenthol = False 
    new_tobacco.save()
    return redirect('/goorm/' +str(new_tobacco.id))

@login_required
def edit(request, tobacco_id) :
    if request.user.username == 'admin':
        edit_tobacco = Tobacco.objects.get(id=tobacco_id)
        return render(request, 'goorm/edit.html', {'tobacco' : edit_tobacco})
    else:
        err = '권한이 없습니다.'
        return render(request, 'accounts/error.html', {'err':err} )


def update(request, tobacco_id):
    update_tobacco = Tobacco.objects.get(id=tobacco_id)
    update_tobacco.name = request.POST['name']
    update_tobacco.price = request.POST['price']
    # update_tobacco.rel_date = request.POST['rel_date']
    update_tobacco.nicotine = request.POST['nicotine']
    update_tobacco.TAR = request.POST['TAR']
    update_tobacco.feel_of_hit = request.POST['feel_of_hit']
    if request.FILES.get('tobacco_img'):
        update_tobacco.img = request.FILES.get('tobacco_img')
    if request.POST['isMenthol'] == 'yes':
        update_tobacco.isMenthol = True
    else:
        update_tobacco.isMenthol = False
    update_tobacco.save()
    return redirect('/goorm/' + str(update_tobacco.id))

@login_required
def delete(request, tobacco_id):
    if request.user.username == 'admin':
        delete_t= Tobacco.objects.get(id = tobacco_id)
        delete_t.delete()
        return redirect('goorm:goormlist')
    else:
        err = '권한이 없습니다.'
        return render(request, 'accounts/error.html', {'err':err} )

def comment_delete(request, comment_id) : 
    delete_comment = Comment.objects.get(id=comment_id)
    delete_comment.delete()
    return redirect('/goorm/' + str(delete_comment.tobacco.id))

def comment_update(request, comment_id):
    update_comment = Comment.objects.get(id=comment_id)
    update_comment.contents = request.POST['edit_text']
    update_comment.score = request.POST['edit_score']
    update_comment.save()
    return redirect('/goorm/' + str(update_comment.tobacco.id))
    
    

def brand_filter(request , brand_id) :
   brand_tobacco=Tobacco.objects.filter(brand = brand_id)
   brand = Brand.objects.get(pk=brand_id)
   return render(request, 'goorm/brand_detail.html' ,{'tobaccos':brand_tobacco, 'brand': brand})    

def search(request):
    if request.GET.get('q'):
        brd = Brand.objects.all()
        grm = Tobacco.objects.all()
        search_type = request.GET.get('fd_name')
        search_data = request.GET.get('q')

        if search_type == 'brand':
            results = brd.filter(brd_name__icontains = search_data)
        elif search_type == 'name':
            results = grm.filter(name__icontains = search_data)

    return render(request, 'goorm/search.html', { 'results': results, 'search_type':search_type})
# Create your views here.

goorm/templates/goorm/brand_detail.html
{% extends 'base.html' %}
{% block content %}
<br>
<br>
<p class="card-text display-4" style="font-family: 'Eoe_Zno_B';">{{brand}}</p>


<div class="row">

    {% for tobacco in tobaccos %}

    <div class="col-lg-3 col-md-6 mb-4">
        <div class="card card_hover h-100">
        <a href="#" style="height: 100%; display: flex; justify-content:center; align-items:center;"><img class="card-img-top" src="{{tobacco.img.url}}" alt=""></a>
        <div class="card-body"  >
            <h4 class="card-title">
            <a class="stretched-link text-muted" href="{% url 'goorm:detail' tobacco.id %}" >{{tobacco.brand}} {{tobacco.name}}</a>
            </h4>
            <h5>{{tobacco.price}}</h5>
            <p class="card-text"></p>
        </div>
        <div class="card-footer" style="text-align: center;">
            <small class="text-muted"></small>
        </div>
        </div>
    </div> 

    {% endfor %}

</div>

<style>
@font-face { font-family: 'Eoe_Zno_B'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_eight@1.0/Eoe_Zno_B.woff') format('woff'); font-weight: normal; font-style: normal; }
</style>



{% endblock %}

goorm/templates/goorm/detail.html
{% extends 'base.html' %}
{% block content %}

<div class="container">

    <!-- 이거는 신버젼 입니다. - 이관형 -->

    <!--여기 부터   -->
    <div class="row">
        <div class="col-lg-2">

        </div>
        <div class="col-lg-4">
            {% if tobacco.img %}
            <img src="{{tobacco.img.url}}"
                style='width:350px; height: 400px; display:block; margin:5px; text-align: center;'>
            {% endif %}
        </div>
        <div class="col-lg-4" style="height: 436px;">
            <table class="table" style="text-align: right; ">
                <table class="table" style="width: 100%;  ">
                    <thead class="thead-light">
                        <tr>
                            <th scope="action">브랜드</th>
                            <th scope="row">{{tobacco.brand.brd_name}}</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <th scope="row">이름</th>
                            <td>{{tobacco.name}}</td>
                        </tr>
                    </tbody>

                    <thead class="thead-light">
                        <tr>
                            <th scope="action">가격</th>
                            <th scope="row">{{tobacco.price}}</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <th scope="row">니코틴</th>
                            <td>{{tobacco.nicotine}}</td>
                        </tr>
                    </tbody>

                    <thead class="thead-light">
                        <tr>
                            <th scope="action">타르</th>
                            <th scope="row">{{tobacco.TAR}}</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <th scope="row">타격감</th>
                            <td>{{tobacco.feel_of_hit}}</td>
                        </tr>
                    </tbody>

                    <thead class="thead-light">
                        <tr>
                            <th scope="action">점수</th>
                            <th scope="row">{{tobacco.score}}</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <th scope="row">맨솔여부</th>
                            <td>{{tobacco.isMenthol}}</td>
                        </tr>
                    </tbody>



                </table>
        </div>
        <div class="col-lg-2">

        </div>


    </div>
    <!--여기까지 이제 그거임 이걸 옴겨야됌  -->


    <!-- 이거는 구버젼 입니다. - 이관형 -->

    <!-- <h3>브랜드 : {{tobacco.brand.brd_name}}</h3>
        <h3>이름 : {{tobacco.name}} </h3>
        <h3>가격 : {{tobacco.price}} </h3>
        <h3>출시일 : {{tobacco.rel_date}} </h3>
        <h3>니코틴 : {{tobacco.nicotine}} </h3>
        <h3>타르 : {{tobacco.TAR}} </h3>
        <h3>타격감 : {{tobacco.feel_of_hit}} </h3>
        <h3>점수 : {{tobacco.score}} </h3>
        <h3>맨솔여부 : {{tobacco.isMenthol}} </h3> -->

    <!-- <div class="nav-scroller py-3 mb-1">
      <nav class="nav d-flex justify-content-center">
    <a class="p-2 text-muted" href="Page1.html">MAN</a>
    <a class="p-2 text-muted" href="page2.html">WOMAN</a>
    <a class="p-2 text-muted" href="page3.html">BAGS</a>
    <a class="p-2 text-muted" href="page4.html">ACC</a>
    <a class="p-2 text-muted" href="page5.html">SALE</a>
    <div class="dropdown"> -->

    <br>
    <div>
        <a class="p-2 text-muted" href="{% url 'goorm:goormlist' %}"> <strong>List</strong></a>
        {% if request.user.username == 'admin'%}
            <a class="p-2 text-muted" href="{% url 'goorm:delete' tobacco.id %}"><strong>Delete</strong></a>
            <a href="{% url 'goorm:edit' tobacco.id %}" class="p-2 text-muted"><strong>Edit</strong></a>
        {% endif %}
    </div>
    <br>
    <hr>
    <!-- 댓글기능 페이지 -->
    <h5>Review</h5>
    <br>
    <!-- 여기에 이미 작성 된 댓글들이 있음 -->
    {% for comment in comments.all %}
    <span>{{comment.writer}}</span> /
    <span>{{comment.contents}}</span> /
    <span>{{comment.score}}</span>
    {% if request.user == comment.writer %}
    <form action="{% url 'goorm:comment_delete' comment.id %}">
        <button class="btn btn-outline-secondary" type="submit">Delete</button>
    </form>

    <details>
        <summary>
            Edit
        </summary>
        <form action="{% url 'goorm:comment_update' comment.id %}" method="post">
            {% csrf_token %}

            <label for="edit_text">contents : </label>
            <input type="text" name="edit_text" value="{{comment.contents}}">

            <input type="text" name="score_val" value="{{comment.score}}" style="display: none;">

            <label for="edit_score">Score : </label>
            <input type="radio" name="edit_score" value="1">1
            <input type="radio" name="edit_score" value="2">2
            <input type="radio" name="edit_score" value="3">3
            <input type="radio" name="edit_score" value="4">4
            <input type="radio" name="edit_score" value="5">5

            <input type="submit" class="btn btn-primary" value="Edit">

        </form>
    </details>
    {% endif %}
    <hr>
    {% endfor %}

    <!-- 만약에 로그인이 들어가있으면 댓글 작성창이 나오는거임  -->
    {% if user.is_authenticated  %}
    {% if cmt_flag == False %}
    <form action="" method="POST">
        {% csrf_token %}
        <img src="{{ request.user.profile_img.url }}" alt="" style="width: 35px; height: 35px; border-radius: 40%;">
        <span style="padding: 5%;">{{request.user.username}}</span>

        <p>Comment <br> <input type="text" name="comment_text" placeholder="댓글을 입력하세요"></p>
        Score <br>
        <input type="radio" name="comment_score" value="1">1
        <input type="radio" name="comment_score" value="2">2
        <input type="radio" name="comment_score" value="3">3
        <input type="radio" name="comment_score" value="4">4
        <input type="radio" name="comment_score" value="5">5
        <br><br>
        <input class="btn btn-outline-secondary" type="submit" name="">
    </form>
    {% else %}
    이미 리뷰를 작성하셨습니다.
    {% endif %}
    {% endif %}

    <!-- 로그인 된 상태에서 로그인이 되어있으면 댓글창이 나옴 -->
</div>

<script>
    $(document).ready(function () {
        //score 데이터를 가져와 radio의 초기값을 설정함.
        var score = $('input[name="score_val"]').val();
        $('input[name="edit_score"]').val([score]);
    });

</script>

{% endblock %}

goorm/templates/goorm/edit.html
{% extends 'base.html' %}
{% block content %}

<h1>글을 수정하는 중입니다. </h1>

    <form action="{% url 'goorm:update' tobacco.id %}" method = "POST" enctype="multipart/form-data">
        {% csrf_token %}
        
        <p>이름 : <input type="text" name="name" value="{{tobacco.name}}"></p>
        <p>가격 : <input type="number" name="price" value="{{tobacco.price}}"></p>
        <!-- <p>출시일 :<input type="date" name="rel_date" value="{{tobacco.rel_date}}"></p> -->
        
        <p>니코틴 : <input type="number" step="0.1" name="nicotine" value = "{{tobacco.nicotine}}"></p>
        
        <p>타르 : <input type="number" step="0.1" name="TAR" value="{{tobacco.TAR}}"></p>
        
        <p>
        타격감 : 
        <input type="text" name="hit_val" value="{{tobacco.feel_of_hit}}" style="display: none;">
        <input type="radio" name="feel_of_hit" value="상">상
        <input type="radio" name="feel_of_hit" value="중">중
        <input type="radio" name="feel_of_hit" value="하">하
        </p>
        
        <p>
        맨솔의 유무 :
        <input type="text" name="menthol_val" value="{{tobacco.isMenthol}}" style="display: none;"> 
        <input type="radio" name="isMenthol" value="yes">Yes
        <input type="radio" name="isMenthol" value="no">No
        </p>

        <p>이미지 : <input type="file" name = "tobacco_img" accept=".jpg, .png, .gif, .jpeg" ></p>
            
        <hr>
        <div class="update">
            <input class="btn btn-dark" type="submit" style="background-color: #2b457a;" value="저장하기">
        </div>
        <br>
    <form>
        
    <script>
        $(document).ready(function () {
        //타격감, 맨솔유무 데이터를 가져와 radio의 초기값을 설정함.
        var hitVal = $('input[name="hit_val"]').val();
        $('input[name="feel_of_hit"]').val([hitVal]);

        var mentholVal = $('input[name="menthol_val"]').val();
        // alert(mentholVal)
        if(mentholVal == 'False') {
            $('input[name="isMenthol"]').val(["no"]); 
        } else {
            $('input[name="isMenthol"]').val(["yes"]); 
        }
        
      });
    </script>

{% endblock %}

goorm/templates/goorm/list.html
{% extends 'base.html' %}
{% block content %}
    <h1>Goorm List</h1>
    {% if request.user.username == 'admin'%}
      <a href = "{% url 'goorm:new' %}" class="p-2 text-muted">새 구름 등록하기</a>
    {% endif %}
    
    <hr>
    <h3>Brand</h3>
    <br>
    <div class ="row">

        {% for brand in brd_list %}
        <div class="col-md-2 col-xs-6 col-md-2 mb-2" style="text-align :center; ">
            <div class="card card_hover" style="width: 100%;" onclick="fnMove('#{{brand.brd_name}}')" >
                <img class="card-img-top" src="{{brand.brd_img.url}}" alt="" style="display: block; margin: 0px auto; margin-top: 10px; width: 70px; border-radius: 40%;">
                <div class="card-body">
                <p class="card-text ">{{brand}}</p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

    <hr>
    {% for brd in brd_grm %}
    <div class="card" style="width: 100%;">
        <div class="card-header" id="{{brd.0}}">
            {{brd.0}}
        </div>
        <ul class="list-group list-group-flush" class="text-muted">
            <li class="list-group-item">
                <div class ="row">
                    {% for grm in brd.1 %}
                      <div class="col-md-3 col-xs-2 mb-2">
                        <div class="card card_hover h-100">
                          <a class="text-muted" href="" style="height: 100%; display: flex; justify-content:center; align-items:center;"><img class="card-img-top" src="{{grm.img.url}}" alt=""></a>
                          <div class="card-body ">
                            <h4 class="card-title">
                              <a class="stretched-link text-muted" href="{% url 'goorm:detail' grm.id %}" >{{grm.brand}} {{grm.name}}</a>
                            </h4>
                            <h5>{{grm.price}}</h5>
                            <p class="card-text"></p>
                          </div>
                          <div class="card-footer" style="text-align: center;">
                            <small class="text-muted star">{{grm.star}}</small>
                          </div>
                        </div>
                      </div> 
                    {% endfor %}
                </div>
            </li>
        </ul>
    </div>
    <hr>
    {% endfor %}


<script>
  // 자동 스크롤링.
  function fnMove(seq) {
      var offset = $(seq).offset().top;
      $('html, body').animate({ scrollTop: offset }, 400);
  }

</script>

{% endblock %}

goorm/templates/goorm/new.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h1>Add Goorm</h1>

    <form action = "{% url 'goorm:create' %}" method = "POST" enctype="multipart/form-data">
        {% csrf_token %} 
        브랜드:
        <select name="brand">
        {% for brand in brands %}
            <option value="{{brand.brd_name}}" >{{brand.brd_name}}</option>
        {% endfor %}
            <option value="isNewBrand" >브랜드 추가</option>
        </select>
        <input type="text" name="newBrand">
        <br><br>
        이름 : <input type="text" name="name">
        <br>
        <br>
        가격 : <input type="number" name="price">
        <br>
        <br>
        출시일 :<input type="date" min="yyy" max="zzz" name="rel_date">
        <br>
        <br> 
        니코틴 : <input type="number" step="0.1" name="nicotine">
        <br>
        <br>
        타르 : <input type="number" step="0.1" name="TAR">
        <br>
        <br>
        타격감 : 
        <input type="radio" name="feel_of_hit" value="상">상
        <input type="radio" name="feel_of_hit" value="중">중
        <input type="radio" name="feel_of_hit" value="하">하
        <br>
        <br>
        맨솔의 유무 : 
        <input type="radio" name="isMenthol" value="yes">Yes
        <input type="radio" name="isMenthol" value="no">No
        <br>
        <br>
        이미지 : <input type="file" name = "tobacco_img" accept=".jpg, .png, .gif, .jpeg">
        <br>
        <br>

    


        <button type="submit">저장하기</button>
    </form>
</div>
{% endblock %}

goorm/templates/goorm/search.html
{% extends 'base.html' %}
{% block content %}

<!--만약에 브랜드를 검색했을때-->
{% if search_type == 'brand' %}
    <h1>브랜드 검색결과</h1>

<div class="row" style="text-align: center;">
    {%for brand in results%}

        <div class="col-lg-3 col-6 mb-4">
            <div class="card card_hover h-100">
            <a href="#" style="height: 100%; display: flex; justify-content:center; align-items:center;"><img class="card-img-top" src="{{brand.brd_img.url}}" alt=""></a>
            <div class="card-body"  >
                <h4 class="card-title">
                <a class="stretched-link text-muted" href="{% url 'goorm:brand_filter' brand.id %}" >{{brand}}</a>
                </h4>
                <p class="card-text"></p>
            </div>
            <div class="card-footer" style="text-align: center;">
                <small class="text-muted"></small>
            </div>
            </div>
        </div> 

    {% endfor %}
</div>

    <!-- 담배 이름을 검색했을때 -->
{% else %}

    <h1>담배 검색결과</h1>

<div class="row" style="text-align: center;">
    {%for tobacco in results%}
        <div class="col-lg-3 col-6 mb-4">
            <div class="card card_hover h-100">
            <a href="#" style="height: 100%; display: flex; justify-content:center; align-items:center;"><img class="card-img-top" src="{{tobacco.img.url}}" alt=""></a>
            <div class="card-body">
                <h4 class="card-title">
                <a class="stretched-link text-muted" href="{% url 'goorm:detail' tobacco.id %}" >{{tobacco.brand}} <br> {{tobacco.name}}</a>
                </h4>
                <h5>{{tobacco.price}}</h5>
                <p class="card-text"></p>
            </div>
            <div class="card-footer" style="text-align: center;">
                <small class="text-muted"></small>
            </div>
            </div>
        </div> 

    {% endfor %}
</div>

{% endif %}

{% endblock %}