Goorm_Project/urls.py
from django.contrib import admin
from django.urls import path, include
import main.views
import accounts.views
import goorm.views
from django.conf import settings
from django.conf.urls.static import static

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('accounts.urls')),
    path('goorm/', include('goorm.urls')),
  
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/',views.signup,name='signup'),
    path('login/',views.login,name='login'),
    path('logout/',views.logout,name='logout'),
    path('edit/<str:profile_name>',views.edit,name='edit'),
    path('update/<str:profile_name>',views.update,name='update'),
    path('mypage/<str:profile_name>', views.mypage, name='mypage'),
    path('error/', views.error, name='error'),
    path('developer/', views.developer, name='developer'),
]

goorm/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'goorm'

urlpatterns = [
    path('goormlist',views.goormlist, name='goormlist'),
    path('<int:tobacco_id>', views.detail, name='detail'),
    path('new', views.new, name='new'),
    path('create', views.create, name='create'),
    path('brand_detail/<str:brand_id>', views.brand_filter, name='brand_filter'),
    path('delete/<int:tobacco_id>', views.delete, name='delete'),
    path('comment_delete/<int:comment_id>', views.comment_delete, name='comment_delete'),
    path('comment_update/<int:comment_id>', views.comment_update, name='comment_update'),
    path('search/', views.search, name='search'),
    path('edit/<int:tobacco_id>', views.edit, name='edit'),
    path('update/<int:tobacco_id>', views.update, name='update'),
]

main/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('',views.home, name = 'home'),
    path('save_log',views.save_log, name='save_log'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django_fields import DefaultStaticImageField

# Create your models here.

class Profile(AbstractUser):
    start_year=models.CharField(max_length=200, null=True)    
    sex= models.CharField(max_length=5, null=True)
    profile_img = DefaultStaticImageField(upload_to='profile_img/', blank=True, default_image_path='images/default_profile_img.png')

accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from django.contrib import auth
from django.utils import timezone
from .models import Profile
from main.models import Buying_Log
from goorm.models import Comment
# Create your views here

def signup(request):
    if request.method == 'POST':
        # User has info and wants an account now!
        if request.POST['password1'] == request.POST['password2']:   
            try:
                user = Profile.objects.get(username=request.POST['username'])
                return render(request, 'signup.html', {'error': 'Username has already been taken'})
            except Profile.DoesNotExist:
                user = Profile.objects.create_user(
                    request.POST['username'], 
                    password=request.POST['password1'], 
                    sex=request.POST['sex'],
                    start_year=request.POST['start_year'],
                    profile_img = request.FILES.get('profile_img')
                    )
                auth.login(request, user)   #로그인 상태를 유지시켜주는 함수임
               

                return redirect('accounts:login')
        else:
            return render(request, 'accounts/signup.html', {'error': 'Passwords must match'})
    else:
        # User wants to enter info
        return render(request, 'accounts/signup.html')
    return render(request, 'home.html')

def login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = auth.authenticate(request, username=username, password=password)
        if user is not None:   #유저가 none 이 아니면은 로그인 조져라  그다음에 홈창으로 가주는거임
            auth.login(request, user)
            return redirect('home')
        else:
            return render(request, 'accounts/login.html', {'error': 'username or password is incorrect.'})
    else:
        return render(request, 'accounts/login.html')

def logout(request):
    auth.logout(request)
    return redirect('home')          #그냥 단순하게 로그아웃 상태가 해체된다


def mypage(request, profile_name):
    mypage_info = Profile.objects.get(username=profile_name)
    logs = Buying_Log.objects.filter(buyer = mypage_info)
    log_list = []
    for b in logs:
       log_list.append(b)
    a = len(log_list)
    money = a*4500 #총 금액
    choices_date = [log.as_dict() for log in logs] # date 값 json으로 보내기
    #이번달 산 담배들
    count = 0
    pick_date = [str(log.date) for log in logs]
    today = timezone.datetime.now()
    str_today = str(today)
    spl_today = str_today.split('-')
    to_month = int(spl_today[1])
    for pick in pick_date:
        spl = pick.split('-')
        sibal = int(spl[1])
        if to_month == sibal:
            count = count+1
    month_buy =count*4500
    #이번달 평균
    average = (count*20)/30

    my_review=Comment.objects.filter(writer=mypage_info)


    return render(request,'accounts/mypage.html',{'mypage_info':mypage_info,'log':log_list,'money':money,'date':choices_date,'month_buy':month_buy,'average':average
    ,'my_review':my_review})


@login_required
def edit(request, profile_name):
    if request.user.username == profile_name:
        edit_mypage=Profile.objects.get(username=profile_name)
        return render(request, 'accounts/edit.html', {'profile':edit_mypage})    
    else:
        err = '권한이 없습니다.'
        return render(request, 'accounts/error.html', {'err':err})    

def update(request, profile_name):
    update_mypage = Profile.objects.get (username = profile_name)
    update_mypage.sex = request.POST['sex']
    update_mypage.start_year = request.POST['start_year']
    if request.FILES.get('profile_img'):
        update_mypage.profile_img = request.FILES.get('profile_img')

    update_mypage.save()
    return redirect('/accounts/mypage/' + str(profile_name))     

def error(request):
    err = '로그인이 필요한 작업입니다! '
    return render(request, 'accounts/error.html', {'err':err})

def developer(request) :
    return render(request,'accounts/developer.html')

accounts/templates/accounts/edit.html
{% extends 'base.html' %}
{% block content %}

<h1>회원 정보 수정하기</h1>

<form action="{% url 'accounts:update' profile.username %}" method="POST" enctype="multipart/form-data">
    {%csrf_token%}
    성별 : 
    <input type="text" name="sex_val" value="{{profile.sex}}" style="display: none;">
    <input type="radio" name="sex" required="required" value="남자">남자
    <input type="radio" name="sex" required="required" value="여자">여자
    <br>
    시작년도 : <input type="month" name="start_year" value="{{profile.start_year}}">
    <br>
    프로필 사진 :
    <input type="file" name="profile_img" accept=".jpg, .jpeg, .png, .gif">
    <br>
    <br>
    <button type="submit">수정하기</button>
</form>

<script>
    $(document).ready(function () {
        //성별데이터를 가져와 radio의 초기값을 설정함.
        var sexVal = $('input[name="sex_val"]').val();
        $('input[name="sex"]').val([sexVal]);
      });

</script>
{% endblock %}

accounts/templates/accounts/error.html
{% extends 'base.html' %}
{% block content %}
    <div style="text-align: center;"> 
        <br>
        <h1 style="color: red;">ERROR!</h1>
        
        <h2>{{err}}</h2>
        {% if err != '권한이 없습니다.' %}
        <br>
        <h3><a href="{% url 'accounts:login' %}">Login</a></h3>
        {% else %}
        <span class="text-muted"> Admin으로 접속 바랍니다. </span>
        
        {% endif %}
        <br><br>
    </div>


{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% block content %}

  <style>
    input[type=password] {

      background-color: #f6f6f6;

      border: none;

      color: #0d0d0d;

      padding: 15px 32px;

      text-align: center;

      text-decoration: none;

      display: inline-block;

      font-size: 16px;

      margin: 5px;

      width: 85%;

      border: 2px solid #f6f6f6;

      -webkit-transition: all 0.5s ease-in-out;

      -moz-transition: all 0.5s ease-in-out;

      -ms-transition: all 0.5s ease-in-out;

      -o-transition: all 0.5s ease-in-out;

      transition: all 0.5s ease-in-out;

      -webkit-border-radius: 5px 5px 5px 5px;

      border-radius: 5px 5px 5px 5px;

    }

    input[type=password]:focus {

      background-color: #fff;

      border-bottom: 2px solid #5fbae9;

    }

    input[type=password]:placeholder {

      color: #cccccc;

    }

    input[type=password] {

      background-color: #f6f6f6;

      border: none;

      color: #0d0d0d;

      padding: 15px 32px;

      text-align: center;

      text-decoration: none;

      display: inline-block;

      font-size: 16px;

      margin: 5px;

      width: 50%;

      border: 2px solid #f6f6f6;

      -webkit-transition: all 0.5s ease-in-out;

      -moz-transition: all 0.5s ease-in-out;

      -ms-transition: all 0.5s ease-in-out;

      -o-transition: all 0.5s ease-in-out;

      transition: all 0.5s ease-in-out;

      -webkit-border-radius: 5px 5px 5px 5px;

      border-radius: 5px 5px 5px 5px;

    }

    input[type=password]:focus {

      background-color: #fff;

      border-bottom: 2px solid #5fbae9;

    }

    input[type=password]:placeholder {

      color: #cccccc;

    }

    /* 여기부터는 아이디 */

    input[type=text] {

      background-color: #f6f6f6;

      border: none;

      color: #0d0d0d;

      padding: 15px 32px;

      text-align: center;

      text-decoration: none;

      display: inline-block;

      font-size: 16px;

      margin: 5px;

      width: 85%;

      border: 2px solid #f6f6f6;

      -webkit-transition: all 0.5s ease-in-out;

      -moz-transition: all 0.5s ease-in-out;

      -ms-transition: all 0.5s ease-in-out;

      -o-transition: all 0.5s ease-in-out;

      transition: all 0.5s ease-in-out;

      -webkit-border-radius: 5px 5px 5px 5px;

      border-radius: 5px 5px 5px 5px;

    }

    input[type=text]:focus {

      background-color: #fff;

      border-bottom: 2px solid #5fbae9;

    }

    input[type=text]:placeholder {

      color: #cccccc;

    }

    input[type=text] {

      background-color: #f6f6f6;

      border: none;

      color: #0d0d0d;

      padding: 15px 32px;

      text-align: center;

      text-decoration: none;

      display: inline-block;

      font-size: 16px;

      margin: 5px;

      width: 50%;

      border: 2px solid #f6f6f6;

      -webkit-transition: all 0.5s ease-in-out;

      -moz-transition: all 0.5s ease-in-out;

      -ms-transition: all 0.5s ease-in-out;

      -o-transition: all 0.5s ease-in-out;

      transition: all 0.5s ease-in-out;

      -webkit-border-radius: 5px 5px 5px 5px;

      border-radius: 5px 5px 5px 5px;

    }

    input[type=text]:focus {

      background-color: #fff;

      border-bottom: 2px solid #5fbae9;

    }

    input[type=text]:placeholder {

      color: #cccccc;

    }
  </style>

  <br>
  <br>
  <!-- header -->
  <div class="jumbotron text-center">
    <h1>GOORM GWAJA<br>PROJECT</h1>
  </div>
  <div style="text-align: center;">
    <h2> <strong>세계최강 담배커뮤니티 구름과자에 오신걸 환영합니다</strong></h2>
    <br>
    <h1 class="text-muted">LOGIN</h1>
</div>

  <!-- 로그인 해놓기  -->
  <div style="text-align: center;">
    <form type="login" method="POST" action="{% url 'accounts:login'%}">
      {% csrf_token %}
      <input type="text" name="username" required="required" placeholder="Your ID"><br>

      <input type="password" name="password" required="required" placeholder="Your password"><br>
      <br>
      <input type="submit" class="btn btn-info" style="width: 20%;" value="Login"><br>
      <br>
      <a href="{% url 'accounts:signup' %}" class="btn btn-Dark" style="width: 20%;">회원가입</a>

    </form>
  </div>


<h1 style="text-align: center;">{{error}}</h1 >

{% endblock %}

accounts/templates/accounts/mypage.html
{% extends 'base.html' %}
{% block content %}

<!-- 달력스크립트 -->
<style type="text/css">
    td {
        width: 50px;
        height: 50px;
        text-align: center;
        font-size: 20px;
        font-family:'BMHANNAAir' !important;
        border: 2px; 
        border-radius: 8px;
        border-color:#929292;
        /* border-color:#b4b4b4; */
        /*모서리 둥글게*/
    }
</style>
<script type="text/javascript">
    var today = new Date();//오늘 날짜//내 컴퓨터 로컬을 기준으로 today에 Date 객체를 넣어줌
    var date = new Date();//today의 Date를 세어주는 역할
    var practice = document.getElementById("buy");
    const date_string = "{{ date }}".replace(/&#39;/g, "\""); //views.py에서 보낸거 받음 스트링으로 보내면 받을수 있나봄, 뒤에 replace는 쓰레기값 바꿔주는 역할인가봄
    const dayday = JSON.parse(date_string) //얘를 parse라는걸 사용해서 객체로 바꿔줌
    var infoarray = []; //배열하나 선언
    for (var x in dayday) {
        var yeah = dayday[x].date;
        var strarray = yeah.split('-');
        yea = Number(strarray[0]);
        mon = Number(strarray[1]);//date객체랑 비교할꺼니까 미리 number로 바꿔둠
        da = Number(strarray[2]);
        infoarray.push({ year: yea, month: mon - 1, day: da });
    }


    function prevCalendar() {//이전 달
        // 이전 달을 today에 값을 저장하고 달력에 today를 넣어줌
        //today.getFullYear() 현재 년도//today.getMonth() 월  //today.getDate() 일 
        //getMonth()는 현재 달을 받아 오므로 이전달을 출력하려면 -1을 해줘야함
        today = new Date(today.getFullYear(), today.getMonth() - 1, today.getDate());
        buildCalendar(); //달력 cell 만들어 출력 
    }

    function nextCalendar() {//다음 달
        // 다음 달을 today에 값을 저장하고 달력에 today 넣어줌
        //today.getFullYear() 현재 년도//today.getMonth() 월  //today.getDate() 일 
        //getMonth()는 현재 달을 받아 오므로 다음달을 출력하려면 +1을 해줘야함
        today = new Date(today.getFullYear(), today.getMonth() + 1, today.getDate());
        buildCalendar();//달력 cell 만들어 출력
    }
    function buildCalendar() {//현재 달 달력 만들기
        var doMonth = new Date(today.getFullYear(), today.getMonth(), 1);
        //이번 달의 첫째 날,
        //new를 쓰는 이유 : new를 쓰면 이번달의 로컬 월을 정확하게 받아온다.     
        //new를 쓰지 않았을때 이번달을 받아오려면 +1을 해줘야한다. 
        //왜냐면 getMonth()는 0~11을 반환하기 때문
        var lastDate = new Date(today.getFullYear(), today.getMonth() + 1, 0);
        //이번 달의 마지막 날
        //new를 써주면 정확한 월을 가져옴, getMonth()+1을 해주면 다음달로 넘어가는데
        //day를 1부터 시작하는게 아니라 0부터 시작하기 때문에 
        //대로 된 다음달 시작일(1일)은 못가져오고 1 전인 0, 즉 전달 마지막일 을 가져오게 된다
        var tbCalendar = document.getElementById("calendar");
        //날짜를 찍을 테이블 변수 만듬, 일 까지 다 찍힘
        var tbCalendarYM = document.getElementById("tbCalendarYM");
        //테이블에 정확한 날짜 찍는 변수
        //innerHTML : js 언어를 HTML의 권장 표준 언어로 바꾼다
        //new를 찍지 않아서 month는 +1을 더해줘야 한다. 
        tbCalendarYM.innerHTML = today.getFullYear() + "년 " + (today.getMonth() + 1) + "월";

        /*while은 이번달이 끝나면 다음달로 넘겨주는 역할*/
        while (tbCalendar.rows.length > 2) {
            //열을 지워줌
            //기본 열 크기는 body 부분에서 2로 고정되어 있다.
            tbCalendar.deleteRow(tbCalendar.rows.length - 1);
            //테이블의 tr 갯수 만큼의 열 묶음은 -1칸 해줘야지 
            //30일 이후로 담을달에 순서대로 열이 계속 이어진다.
        }
        var row = null;
        row = tbCalendar.insertRow();
        //테이블에 새로운 열 삽입//즉, 초기화
        var cnt = 0;// count, 셀의 갯수를 세어주는 역할
        // 1일이 시작되는 칸을 맞추어 줌
        for (i = 0; i < doMonth.getDay(); i++) {
            /*이번달의 day만큼 돌림*/
            cell = row.insertCell();//열 한칸한칸 계속 만들어주는 역할
            cnt = cnt + 1;//열의 갯수를 계속 다음으로 위치하게 해주는 역할
        }
        /*달력 출력*/
        for (i = 1; i <= lastDate.getDate(); i++) {
            //1일부터 마지막 일까지 돌림
            cell = row.insertCell();//열 한칸한칸 계속 만들어주는 역할
            cell.innerHTML = i;//셀을 1부터 마지막 day까지 HTML 문법에 넣어줌
            cnt = cnt + 1;//열의 갯수를 계속 다음으로 위치하게 해주는 역할
            if (cnt % 7 == 1) {/*일요일 계산*/
                //1주일이 7일 이므로 일요일 구하기
                //월화수목금토일을 7로 나눴을때 나머지가 1이면 cnt가 1번째에 위치함을 의미한다
                cell.innerHTML = "<font color=#F79DC2>" + i
                //1번째의 cell에만 색칠
            }
            if (cnt % 7 == 0) {/* 1주일이 7일 이므로 토요일 구하기*/
                //월화수목금토일을 7로 나눴을때 나머지가 0이면 cnt가 7번째에 위치함을 의미한다
                cell.innerHTML = "<font color=skyblue>" + i
                //7번째의 cell에만 색칠
                row = calendar.insertRow();
                //토요일 다음에 올 셀을 추가
            }
            /*오늘의 날짜에 노란색 칠하기*/
            if (today.getFullYear() == date.getFullYear()
                && today.getMonth() == date.getMonth()
                && i == date.getDate()) {
                //달력에 있는 년,달과 내 컴퓨터의 로컬 년,달이 같고, 일이 오늘의 일과 같으면
                cell.style.border = "3px solid #FAF58C";//셀의 배경색을 노랑으로 
                cell.style.borderRadius = "5px";
            }

            var grm_cnt = {};
            grm_cnt['count'] = 0;
            for (var a in infoarray) {
                if (today.getFullYear() == infoarray[a].year
                    && today.getMonth() == infoarray[a].month
                    && i == infoarray[a].day)

                    cell.bgColor = "#b4b4b4";
                    // cell.style.backgroundColor = "red";
                    

            }
        }

    }
    // 여기까지 달력이 였습니다.
   
</script>

<div class="container">
    


<!-- 로우 하나에 마이페이지랑 달력이랑 묵음 -->
<div class="row">
    <div class="col-lg-2">

    </div>
    <div class="col-lg-4" style="text-align: center;">
        <p><img style="width: 13.5rem; border-radius: 25%;" src="{{ mypage_info.profile_img.url }}"></p>
        <p>ID : {{ mypage_info.username }}</p>
        <p>성별 : {{mypage_info.sex }}</p>
        <p>흡연시작년도 : {{mypage_info.start_year}}</p>

        <p><a class="p-10 text-muted" href="{% url 'accounts:edit' mypage_info.username %}">회원정보 수정하기</a>
        </p>
    </div>

    <div class="col-lg-4">
        <br>
        <!-- <div class="card">
            내가 평가한 담배 리스트 :
            {% for tmp in my_review %}
            <a href="#"><img src="{{tmp.tobacco.img.url}}" alt=""
                    style="width: 35px; height: 35px; border-radius: 40%; vertical-align: top;">{{tmp.tobacco}}
                ></a>
            {% endfor %}
        </div> -->
        <div class="list-group mb-3" style="max-width: 540px;">
            <a href="#" class="list-group-item list-group-item-secondary list-group-item-action disabled" tabindex="-1"
                aria-disabled="true" style="text-align: center;">
                <h5><strong>내가 평가한 담배들</strong></h5>
            </a>
            {% for tmp in my_review %}
            <a href="{% url 'goorm:detail' tmp.tobacco.id %}" class="list-group-item list-group-item-action" style="padding-left: 15%;">
                <img src="{{tmp.tobacco.img.url}}" alt=""
                    style="width: 35px; height: 35px; border-radius: 40%; vertical-align: top;">
                {{tmp}}
            </a>
            {% endfor %}
        </div>
    </div>

</div>

</div>

<hr>
<br>

<!-- 달력시작 -->

<h2 align="center">★Goorm Calender★</h2>
<table id="calendar" border="3" align="center" style="border-color:#929292; ">
    <tr>
        <!-- label은 마우스로 클릭을 편하게 해줌 -->
        <td><label onclick="prevCalendar()">
                <</label> </td> <td align="center" id="tbCalendarYM" colspan="5">
                    yyyy년 m월</td>
        <td><label onclick="nextCalendar()">>

            </label></td>
    </tr>
    <tr>
        <td align="center">
            <font color="#F79DC2">일
        </td>
        <td align="center">월</td>
        <td align="center">화</td>
        <td align="center">수</td>
        <td align="center">목</td>
        <td align="center">금</td>
        <td align="center">
            <font color="skyblue">토
        </td>
    </tr>
</table>
<br><br>
<!-- 달력 끝 -->

<div class="p-2 text-muted" style="text-align: center;">
    <h2> 당신은 지금까지 담배에 <strong>{{money}}</strong>원을 쓰셨습니다. </h2>
    <h2> 당신은 이번 한달동안 담배에 <strong>{{month_buy}}</strong>원을 쓰셨습니다. </h2>
    <h2> 당신은 이번달 하루 평균 <strong>{{average}}</strong>개피의 담배를 피셨습니다. </h2>
</div>
<br>

</div>

<script language="javascript" type="text/javascript">
    buildCalendar();//
</script>


{% endblock %}