Goorm_Project/urls.py
from django.contrib import admin
from django.urls import path, include
import main.views
import accounts.views
import goorm.views
from django.conf import settings
from django.conf.urls.static import static

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('accounts.urls')),
    path('goorm/', include('goorm.urls')),
  
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/',views.signup,name='signup'),
    path('login/',views.login,name='login'),
    path('logout/',views.logout,name='logout'),
    path('edit/<str:profile_name>',views.edit,name='edit'),
    path('update/<str:profile_name>',views.update,name='update'),
    path('mypage/<str:profile_name>', views.mypage, name='mypage'),
    path('error/', views.error, name='error'),
    path('developer/', views.developer, name='developer'),
]

goorm/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'goorm'

urlpatterns = [
    path('goormlist',views.goormlist, name='goormlist'),
    path('<int:tobacco_id>', views.detail, name='detail'),
    path('new', views.new, name='new'),
    path('create', views.create, name='create'),
    path('brand_detail/<str:brand_id>', views.brand_filter, name='brand_filter'),
    path('delete/<int:tobacco_id>', views.delete, name='delete'),
    path('comment_delete/<int:comment_id>', views.comment_delete, name='comment_delete'),
    path('comment_update/<int:comment_id>', views.comment_update, name='comment_update'),
    path('search/', views.search, name='search'),
    path('edit/<int:tobacco_id>', views.edit, name='edit'),
    path('update/<int:tobacco_id>', views.update, name='update'),
]

main/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('',views.home, name = 'home'),
    path('save_log',views.save_log, name='save_log'),
]

Goorm_Project/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% load static %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Goorm Project</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static './vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <script src="http://code.jquery.com/jquery-latest.min.js"></script>
  <script type="text/javascript" src="http://code.jquery.com/jquery-latest.js"></script>
  <style>
    @font-face {
      font-family: 'BMHANNAAir';
      src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_four@1.0/BMHANNAAir.woff') format('woff');
      font-weight: normal;
      font-style: normal;
    }

    body {
      font-family: 'BMHANNAAir';
    }
    
  </style>

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="{% url 'home' %}">Goorm Project</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
        aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">

          <!--담배기능 리스트 작업-->

          <li class="nav-item active" style="text-align: center;" >
            <a class="nav-link " href="{% url 'goorm:goormlist' %}">Goorm List
              <span class="sr-only">(current)</span>
            </a>
          </li>

          {% if request.user.username == 'admin' %}
          <li class="nav-item active" >
            <a class="nav-link" href="{% url 'goorm:new' %}" >Add Goorm
              <span class="sr-only">(current)</span>
            </a>
          </li>
          {% endif %}

          <!--담배기능 리스트 작업-->


          <!-- 네비바 검색기능 -->


          <!--로그인 기능 네브바-->

          {% if user.is_anonymous %}
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'accounts:login' %}">로그인
              <span class="sr-only">(current)</span>
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:signup' %}">회원가입</a>
          </li>

          {% elif user.is_authenticated  %}

          <li class="nav-item">
            <form id="logout" method="POST" action="{% url 'accounts:logout' %}" class="nav-link" style="text-align: center;">
              {% csrf_token %}
              <input type="submit" class="btn btn-secondary" value="Logout">
            </form>
          </li>

          <a class="nav-link" href="{% url 'accounts:mypage' user.username %}">
            <div style="text-align: center;">
              <img src="{{ request.user.profile_img.url }}" alt=""
                style="width: 35px; height: 35px; border-radius: 40%; vertical-align: top;">
            </div>
          </a>

          {% endif %}

          <!-- 네비바 검색기능 -->
          <form class="form-inline" action="{% url 'goorm:search'%}" method="get">
            <div class="input-group">
              <select name="fd_name" id="" class="form-control">
                <option value="brand">brand</option>
                <option value="name">name</option>
              </select>
              <br>
              <input type="text" class="form-control" name='q' required='required'>
              <button class="btn btn-secondary" type="submit">Search</button>
            </div>
          </form>

        </ul>
      </div>
    </div>
  </nav>

  <div class="container">
    {% block content %}
    {% endblock %}
  </div>


  <!-- Footer -->
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white"> Copyright &copy; Project Goorm 2020 </p>

      <p class="m-0 text-right text-white"> <a href="{% url 'accounts:developer' %}">Developer</a>></p>


    </div>
    <!-- /.container -->
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static './vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static './vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script>
    $(document).ready(function () {
      // executes when HTML-Document is loaded and DOM is ready
      // console.log("document is ready");

      $(".card_hover").hover(function () {
        $(this).addClass('shadow').css('cursor', 'pointer');
      }, function () {
        $(this).removeClass('shadow');
      });
    });
  </script>

</body>

</html>

<style>
  body {
    padding-top: 80px;
    box-sizing: border-box;
  }

  .card:hover {
    text-decoration: none;
  }

  .star {
    font-family: Georgia !important;
  }
</style>